### PR TITLE
[fixes #509] Fix Component Analysis Dialog

### LINKED ISSUE #509: Fix Component Analysis Dialog to work with instanced components.
Continuation of #397:  Experimental branch to work on fixing this window in an acceptable way.
----

Discussion:
====
Take, for instance, net.sf.openrocket.masscalc.MassCalculator#getCGAnalysis(...)@130:

It currently returns a map of RocketComponent => Coordinate (of CG)...
This worked fine for simple object hierarchies, but once we implemented instanced objects, one Component may correspond to multiple locations and CGs.

If we have a rocket with doubly instanced components, like so:
```
- rocket 
  - nose
  - body
    - boosters (x2)
      - booster nose
      - booster body
        - booster fins (x3)
```
What, logically, should that analysis output?

- an aggregated analysis of the average cg?
(including the total, centers of mass of all the boosters combined, and the aggregate total and center of mass for the fins.)

### clarifying: 
- something like a column for the mass of a booster, 
- second column giving the aggregate mass
- current table appears to be listing the components in the order given by a bread-first search of the tree representing the design; a more tree-like view would seem better.

### PR DESCRIPTION
**Pull request by teyrana**
### Example
Draft5

### Current Jar

[Openrocket-509-fix-analysis.jar]( https://drive.google.com/file/d/1w1hQl0SozbZrvuGWa-MP25UXPYNp8TOZ/view?usp=sharing )

### Todos
- [X] Re Enable Dialog
- [X] Fix the Mass Calculation Analysis Code
- [x] Display Components in the same order as the component tree
- [x] Re-enable aerodynamic calculations
    - [x] Refactor `BarrowmanCalculator.getForceAnalysis`
    - [x] Enable calculations for `ComponentAssembly` classes
    - [x] Enable CD calculations in `getForceAnalysis`
    - [x] fix Nan -> 0 copying for CPx, CNa on non-assembly, non-aerodynamic components
    - [x] fix Nan -> 0 copying for CPx, CNa on motors
- [x] Restore 'Drag Characteristics' Tab
   - [x] Correct % numbers
- [x] Restore 'Roll Dynamics' Tab

### CODE REVIEW

**Comment by teyrana** [comment]
## Aerodynamic Calculations

WIP: this is the call stack for obtaining the Aerodynamic Force Analysis data:

1. ComponentAnalysisDialog.stateChanged:504
2. BarrowmanCalculator.getForceAnalysis: 67
3. BarrowmanCalculator.calculateNonAxialForces:156

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java [hunk 1]
```diff
@@ -559,21 +548,28 @@ public void stateChanged(EventObject e) {
...
+				row.cpx = forces.getCP().x;
+				row.cna = forces.getCNa();
+			}
+
+//			System.err.println(String.format("        .CD = %s", forces.getCD()));
+			if (!Double.isNaN(forces.getCD())) {
+				dragData.add(forces);
+			}
+
+			if (comp instanceof FinSet) {
```
Comment (wolsen) [inline swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:576]: Does this need to apply to TubeFinSets as well? They aren't part of the FinSet hierarchy...

edit: Thinking a bit about it, the TubeFinSets don't have a cant property so its likely this won't apply there. So I think the comment is moot, but leaving it here for others to agree or refute.

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java [hunk 2]
```diff
@@ -186,69 +182,72 @@ public void stateChanged(ChangeEvent e) {
...
 				//// Component
 				new Column(trans.get("componentanalysisdlg.TabStability.Col.Component")) {
 					@Override
 					public Object getValueAt(int row) {
-						Object c = cgData.get(row)[0];
-						if (c instanceof Rocket) {
-							return trans.get("componentanalysisdlg.TOTAL");
-						}
+						Object c = stabData.get(row).name;
+//						if (c instanceof Rocket) {
```
Comment (wolsen) [inline swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:192]: commented out code can be removed

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java [hunk 3]
```diff
@@ -534,65 +531,78 @@ public void stateChanged(EventObject e) {
...
+
+		for(final RocketComponent comp: configuration.getAllComponents()) {
+			// // this is actually redundant, because the analysis will not contain inactive stages.
+			// if (!configuration.isComponentActive(comp)) {
+			// 	continue;
+			// }
+
+			CMAnalysisEntry cmEntry = cmMap.get(comp.getName());
+			if (null == cmEntry) {
+				System.err.println("Could not find entry for component: " + comp.getName());
```
Comment (wolsen) [inline swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java]: Send to logs instead of stderr

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java [hunk 4]
```diff
@@ -698,6 +707,25 @@ public Component getTableCellRendererComponent(JTable table, Object value,
 		}
 	}
 
+	private class LongitudinalStabilityRow {
```
Comment (wolsen) [inline swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:715]: +1 to this - much cleaner

File: core/src/net/sf/openrocket/masscalc/MassCalculation.java [hunk 5]
```diff
@@ -273,9 +289,16 @@ MassCalculation calculateStructure() {
 		// if( this.config.isComponentActive(component) ){
 		// 	System.err.println(String.format( "%s>>[%s]....", prefix, component.getName()));
 		// }
-		
+
+		if(null != analysisMap) {
+			if (this.config.isComponentActive(component) && (! analysisMap.containsKey(component.getName()))){
+				CMAnalysisEntry entry = new CMAnalysisEntry(component);
+				analysisMap.put(component.getName(), entry);
```
Comment (wolsen) [inline core/src/net/sf/openrocket/masscalc/MassCalculation.java:296]: The component.getName() is not sufficiently unique, I think you'll need component.getID(). Multiple components can have the same name (in fact, the default name for components is chosen by default). Come to think of it, I wonder if we have this problem elsewhere.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java [hunk 6]
```diff
@@ -64,68 +57,129 @@ public BarrowmanCalculator newInstance() {
...
+		AerodynamicForces aggregateForces = new AerodynamicForces().zero();
+		aggregateForces.setComponent(comp);
+
+//		System.err.println(">>>> comp=" + comp.getName());
+
+		// forces for this component, _only_
+		if(comp.isAerodynamic()) {
+			RocketComponentCalc calcObj = calcMap.get(comp);
+			if (null == calcObj) {
+				System.err.println("Could not find a CalculationObject for aerodynamic Component!: " + comp.getComponentName());
```
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:154]: Yup.  Todo.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java [hunk 7]
```diff
@@ -150,73 +204,90 @@ public AerodynamicForces getAerodynamicForces(FlightConfiguration configuration,
...
-	
+
+
+	private AerodynamicForces calculateComponentNonAxialForces( FlightConditions conditions,
+																RocketComponent comp,
+																RocketComponentCalc calcObj,
+																List<InstanceContext> contextList,
+																WarningSet warnings)
+	{
+//		System.err.println(String.format("@@ comp=%s    =>    %s", comp.getName(), calcObj.getClass().getSimpleName()));
```
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:218]: I'll strip most of these printlns once the results are as desired.

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java (hunk 1 above)
Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:576]: Yea, I agree on both.   I'll add a comment for clarity.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java [hunk 8]
```diff
@@ -64,68 +57,129 @@ public BarrowmanCalculator newInstance() {
...
-		return map;
+
+		return finalMap;
 	}
-	
-	
-	
+
+	private AerodynamicForces calculateForceAnalysis(   FlightConditions conds,
+														RocketComponent comp,
```
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:137]: It's on "auto"  which usually does a good job of matching what's in the file, but _does_ sometimes get overzealous...

[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:137]: Also, the project really doesn't have even a de-facto standard about trailing spaces on empty lines.   I think eclipse adds spaces to match surrounding indents, and intellij removes trailing spaces on empty lines.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:154]: Okay, converted to throw an npe.   

I'm trying to decide between that and just logging an error...  My rationale is that this is a pretty serious bug, if it happens, and the entire dialog is probably invalid at this point, anyway.  

Thoughts?

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java:218]: So, you're right, but I don't want to remove them, yet.

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java (hunk 1 above)
Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:576]: added a comment block right aftewards:
```
			// // We _would_ check this, except TubeFinSet doesn't implement cant angles... so they can't impart any roll torque
			// // If this is ever implemented, uncomment this block:
			// else if(comp instanceof TubeFinSet){
			// 	rollData.add(forces)
			// }
```

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java (hunk 2 above)
Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java:192]: previous versions of this dialog labeled this row as "Total" instead of the rocket name.  

I left this in, in case people objected and wished for the previous behavior.
Seeing no objections: removed.

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java (hunk 3 above)
Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java]: Temporary debugging line.  Will be removed before merging.

Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java]: (meaning, I don't believe this is significant enough to warrant a log line.)

File: core/src/net/sf/openrocket/masscalc/MassCalculation.java (hunk 5 above)
Comment (teyrana) [reply core/src/net/sf/openrocket/masscalc/MassCalculation.java:296]: Yea, I'd tried that, but it broke.  

But, It's still a valid point.  I'll convert that over.

Comment (teyrana) [reply core/src/net/sf/openrocket/masscalc/MassCalculation.java]: seems to work.   marking as resolved.

**Comment by teyrana** [comment]
Updated per @wolsen 's comments.

FYI, there are some clean up tasks I'm holding off on, until people are okay with the layout, and calculations.
- [ ] Numerous `System.err.println` statements. Those will be gone
- [ ] Squashing commits into 1, for the PR.

**Comment by teyrana** [comment]
@wolsen 
Nobodies raised major issues with this PR, so I've addressed the remainder of your comments, and would like to merge it, if you're happy.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java]: Seeing no objection, resolving.

File: core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (teyrana) [reply core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java]: All System.err.println statements in this patch have been removed.

File: swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java (hunk 3 above)
Comment (teyrana) [reply swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java]: Removed.

**Comment by teyrana** [comment]
@wolsen 
Okay, I've made the rest of the changes you requested. 
Given we haven't found any breaking changes, I'm going to merge into mainline, for the next RC.
